# Generated by Django 5.1 on 2024-08-08 21:28

import child_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='blood_type',
            field=models.CharField(max_length=3, validators=[child_app.validators.validate_blood_type]),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
