# Generated by Django 5.1 on 2024-08-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0003_alter_child_blood_type_alter_child_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='child',
            name='allergies',
            field=models.TextField(blank=True),
        ),
    ]
